# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Members
    url: members
    weight: 10
  - name: News
    url: post
    weight: 20
  - name: Projects
    url: project
    weight: 30
  - name: Publications
    url: publication
    weight: 40
  - name: Lab Wiki
    url: wiki
    weight: 50
  - name: Reading Group
    url: dbrg
    weight: 60
  - name: Contact
    url: contact
    weight: 70